### ISSUE TITLE
Throws error with httpie 0.9.7+

### ISSUE THREAD

**Issue by sonicoder86** [emartech/httpie-ems-auth#1]
Installing HTTPie version 0.9.7 or higher breaks the request.

```bash
Traceback (most recent call last):
  File "/usr/local/bin/http", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/httpie/core.py", line 210, in main
    parsed_args = parser.parse_args(args=args, env=env)
  File "/usr/local/lib/python2.7/site-packages/httpie/input.py", line 168, in parse_args
    self._process_auth()
  File "/usr/local/lib/python2.7/site-packages/httpie/input.py", line 268, in _process_auth
    password=credentials.value,
TypeError: get_auth() got an unexpected keyword argument 'username'
```

**Comment by ghost** [comment]
Same thing, httpie 0.9.9, using Python 3.6.4, with wsse-auth plugin from https://github.com/emartech/httpie-wsse-auth
